# -*- coding: UTF-8 -*-
__author__ = 'biyanbing'

_tag = u'标签'
_category = u'分类'
_created_time = u'创建时间'
_update_time = u'更新时间'
_name = u'名称'

_product = '产品'
_title = u'标题'
_content = u'内容'
_cover = u'封面'
_vote_up = u'顶次数'
_vote_down = u'踩次数'
_share = u'分享次数'
_status = u'状态'
_ok = '正常'
_waiting = '等待审核'
_close = '关闭'
